# superuser permission
sudo: required
services:
  - docker

before_install:
  - docker build -t orenkole/docker-react -f Dockerfile.dev .

script:
  - docker run orenkole/docker-react npm run test -- --coverage
